"""create inspection table

Revision ID: d5097882b38e
Revises:
Create Date: 2026-09-22 10:03:49.209871

─────────────────────────────────────────────────────────────────────────────
이 파일은 무엇을 하는가
  첫 마이그레이션. 검사 이력 표 inspection 을 만든다 (upgrade) / 지운다 (downgrade).
  `alembic revision --autogenerate -m "create inspection table"` 이 models.py 의 Inspection 과
  빈 DB 를 비교해 자동으로 써 준 파일이다. 사용자가 읽고 확인한 뒤 `alembic upgrade head` 로 적용했다 (2026-09-22).
  주석만 Claude 가 추가했고 코드는 자동 생성 그대로다.

프로젝트 실행 흐름에서 어느 위치인가
  models.py (설계) ──autogenerate──▶ [현재 파일] ──upgrade head──▶ 실제 DB 의 inspection 표
  앞: migrations/env.py 가 db.build_url() 로 접속하고 Base.metadata 에서 설계를 읽는다.
  뒤: 표가 생긴 뒤 main.py 가 검사마다 행을 넣는다. 이 파일은 다시 실행되지 않는다
      (alembic_version 표에 d5097882b38e 가 기록되어 "이미 적용됨" 으로 처리된다).
  ★ 적용된 마이그레이션 파일은 고치지 않는다. 표를 바꾸려면 models.py 를 고치고 새 마이그레이션을 만든다.

이 파일을 이해하기 전에 알아야 할 개념
  revision      : 이 마이그레이션의 고유 번호. 파일 이름 가운데의 d5097882b38e. git 의 커밋 해시와 같은 역할.
  down_revision : 바로 앞 마이그레이션의 번호. None 이면 첫 번째라는 뜻. 다음 마이그레이션의 down_revision 이 d5097882b38e 가 된다.
                  이 연결로 Alembic 이 적용 순서를 안다.
  op            : Alembic 이 주는 "DB 구조를 바꾸는 명령 모음". op.create_table → CREATE TABLE, op.drop_table → DROP TABLE.
  sa.Column     : 컬럼 하나. models.py 의 mapped_column 한 줄이 여기서 sa.Column 한 줄로 바뀌어 있다.
─────────────────────────────────────────────────────────────────────────────
"""
# 타입 표시(revision: str 등)에 쓰는 표준 라이브러리. 자동 생성 틀이 넣은 것이다.
from typing import Sequence, Union

# op : DB 구조 변경 명령 모음.
from alembic import op
# sa : SQLAlchemy 전체를 짧은 이름으로. sa.Column, sa.Integer 처럼 쓴다.
import sqlalchemy as sa
# mssql : SQL Server 전용 타입(DATETIME2)을 가져오는 방언 모듈. models.py 와 같은 곳에서 온다.
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
# 이 마이그레이션의 번호. 파일 이름과 alembic_version 표의 값과 같다.
revision: str = 'd5097882b38e'
# 앞 마이그레이션 없음 = 첫 번째.
down_revision: Union[str, Sequence[str], None] = None
# 가지(branch) 이름과 의존 관계. 마이그레이션이 한 줄로 이어지는 우리 프로젝트에서는 쓰지 않는다.
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    `alembic upgrade head` 가 부른다. 표 inspection 을 만든다.
    입력: 없음.  출력: 없음. DB 에 CREATE TABLE inspection (...) 이 실행된다.
    실패 시: 같은 이름의 표가 이미 있으면 SQL Server 가 거절한다 (ProgrammingError). 트랜잭션이라 반쯤 만들어지지 않는다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # 아래 10 줄은 models.py 의 컬럼 10 개와 1:1 로 대응한다. 순서도 같다.
    op.create_table('inspection',
    # 기본 키. 정수 PK 는 SQL Server 에서 IDENTITY(자동 번호)가 붙는다. 맨 아래 PrimaryKeyConstraint 가 PK 를 지정한다.
    sa.Column('id', sa.Integer(), nullable=False),
    # server_default=sa.text('sysdatetime()') : DB 쪽 기본값. models.py 의 func.sysdatetime() 이 SQL 글자로 바뀐 것.
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysdatetime()'), nullable=False),
    # 'OK' / 'NG'. Unicode(2) → NVARCHAR(2).
    sa.Column('result', sa.Unicode(length=2), nullable=False),
    # 모델이 센 개수 셋.
    sa.Column('bolt_count', sa.Integer(), nullable=False),
    sa.Column('nut_count', sa.Integer(), nullable=False),
    sa.Column('washer_count', sa.Integer(), nullable=False),
    # 요청에 담겨 온 기대 개수 셋.
    sa.Column('bolt_expected', sa.Integer(), nullable=False),
    sa.Column('nut_expected', sa.Integer(), nullable=False),
    sa.Column('washer_expected', sa.Integer(), nullable=False),
    # 판정한 YOLO 모델 이름. Unicode(50) → NVARCHAR(50).
    sa.Column('model_name', sa.Unicode(length=50), nullable=False),
    # id 를 기본 키로. CREATE TABLE 의 PRIMARY KEY (id) 에 해당한다.
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    `alembic downgrade -1` 이 부른다. upgrade 를 되돌려 표 inspection 을 지운다.
    입력: 없음.  출력: 없음. DB 에 DROP TABLE inspection 이 실행된다.
    ⚠️ 표 안의 검사 이력도 전부 사라진다. 운영 데이터가 쌓인 뒤에는 함부로 실행하지 않는다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection')
    # ### end Alembic commands ###
